# Generated by Django 5.2.7 on 2025-11-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CirculumVitae',
            new_name='Candidate',
        ),
    ]
