# Generated by Django 5.2.7 on 2025-11-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_circulumvitae_candidate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidate',
        ),
    ]
